# action.yaml
name: 'Elvia sesam node validation'
description: 'A GitHub Action that validates configs to be used in Sesam node (target node)'
env:
  CI_NODE: ${{ inputs.ci_node }}
  CI_JWT: ${{ inputs.ci_jwt }}
  NODE: ${{ inputs.node }}
  JWT: ${{ inputs.jwt }}
  WORKSPACE: ${{ inputs.workspace }}

inputs:
  ci_node:
    description: 'URL of api rest endpoint for sesam dev-node used for CI (CI node)'
    required: true
    default: "" # 
  ci_jwt:
    description: 'JWT token'
    required: true
    default: "" #
  node:
    description: 'URL of api rest endpoint for sesam node you want to check against (target node)'
    required: true
    default: "" #
  jwt:
    description: 'A read only JWT token for target node'
    required: true
    default: "" #
  workspace:
    description: 'Workspace name'
    required: true
    default: $GITHUB_WORKSPACE #
  sesam_args:
    description: 'Arguments to pass to sesam-py validate command'
    required: false
    default: "-version" #
  
outputs:
  report:
    description: 'Summary of the validation'

runs:
  using: 'docker'
  dockerfile: 'Dockerfile'
  args:
    - ${{ inputs.sesam_args }}
