services:
  sesam:
    image: mofsesam/elvia-validate
    build: .
    environment:
      - NODE=${NODE}
      - JWT=${JWT}
    command: ["-version"]
    volumes:
      - ./github/workspace:/github/workspace