# .github/workflows/test_action.yaml
name: Test Action

on:
  workflow_dispatch: # allow manual trigger of workflow

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run sesam-py 
        id: sesam_py
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: 3lvia/sesam-validate-action@v1
        with:
          ci_node: "${{ vars.ci_node }}"
          ci_jwt: "${{ secrets.ci_jwt }}"
          sesam_args: "-version"