# .github/workflows/test_action.yaml
name: Test Action

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run sesam-py 
        id: sesam_py
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: 3lvia/sesam-validate-action@v1
        with:
          ci_node: "${{ vars.ci_node }}"
          ci_jwt: "${{ secrets.ci_jwt }}"
          sesam_args: "-version"
        # run: |
        #   echo "Sesam-Py version: ${{ steps.sesam_py.outputs.version }}"
        #   echo "Sesam-Py status: ${{ steps.sesam_py.outputs.status }}"
        #   echo "Sesam-Py message: ${{ steps.sesam_py.outputs.message }}"